trainer:
  batch_size: 2

data_loader:
  out_img_dir: /mnt/liangjm/SpR_data/
  train_ratio: 0.7
  val_ratio: 0.1
  test_ratio: 0.2
  patch_num: 100  # 每个 WSI 切取的 patch 数量
  num_workers: 0
  pin_memory: False
  split_seed: 2025
  # CLAM for WSI 切片参数
  patch_size: 512
  step_size: 512
  down_scale: 4   # 设定 LR 较之 HR 的缩放比例
  min_tissue_ratio: 0.8 # 设定切片时的最小组织比例
  patch_level: 0  # 设定切片时所用的层级, 0 通常是最高分辨率, 40x



TCGA_LUAD:
  root: /mnt/lwx/pyworkspace/multi-sur/data/TCGA-LUAD/
  choose_WSI: 3

TCGA_KIRC:
  root: /mnt/lwx/pyworkspace/multi-sur/data/TCGA-KIRC/
  choose_WSI: 3

TCGA_LIHC:
  root: /mnt/lwx/pyworkspace/multi-sur/data/TCGA-LIHC/
  choose_WSI: 3

  
  